(function(){
'use strict';
const THEMES={
Light:['#0b1d36','#1656a0','#75a900','#d7dee8','#f3f6f9','#ffffff','#0b1d36','#0b1d36','#2e7d32','#f59e0b','#c62828','#111827'],
Dark:['#e7eef8','#60a5fa','#a3e635','#3b4658','#111827','#1f2937','#070d18','#2563eb','#22c55e','#fbbf24','#ef4444','#f8fafc'],
Patriotic:['#102a56','#1f5ca8','#b22234','#b8c7dc','#edf3fa','#ffffff','#102a56','#b22234','#287a3b','#d99b16','#b22234','#14213d'],
Executive:['#222831','#4b5563','#b08d57','#c9c3b8','#eeeae2','#fffdf8','#222831','#725b3b','#3e7354','#b57a1a','#9d3030','#252525'],
Forest:['#173f2a','#2f6b45','#8ba446','#b8c9b7','#eef4ed','#ffffff','#173f2a','#2f6b45','#3e7c42','#c28a23','#a53b35','#17251c'],
Ocean:['#073b4c','#087e8b','#20b7c9','#b6d7dc','#eaf7f8','#ffffff','#073b4c','#087e8b','#25875a','#e39b26','#bd3a4a','#102a33'],
Midnight:['#dce7ff','#7986cb','#b388ff','#34365a','#0e1026','#191b38','#090a19','#5c6bc0','#4caf78','#ffb74d','#ef5350','#f1f4ff'],
'High Contrast':['#000000','#0047ff','#ffe600','#000000','#ffffff','#ffffff','#000000','#0047ff','#006b2d','#9a5b00','#c00000','#000000']
};
const CK=['primary','secondary','accent','border','background','card','menu','button','success','warning','danger','text'];
Object.keys(THEMES).forEach(n=>THEMES[n]=Object.fromEntries(CK.map((k,i)=>[k,THEMES[n][i]])));
const clone=x=>JSON.parse(JSON.stringify(x)), nowYear=()=>new Date().getFullYear(), date=()=>new Date().toISOString().slice(0,10);
function ensure(){
 db.org={profile:'vfw',name:'VFW Post 2924',number:'2924',department:'California',fiscalYearStart:'07-01',...db.org};
 db.categories=Array.isArray(db.categories)?db.categories:[
  {id:uid(),name:'Canteen',active:true,subcategories:['Beer','Liquor','Wine','Soft Drinks','Snacks','Cleaning Supplies']},
  {id:uid(),name:'Kitchen',active:true,subcategories:['Meat','Produce','Dairy','Paper Goods']},
  {id:uid(),name:'Building',active:true,subcategories:['Electrical','HVAC','Repairs','Maintenance']},
  {id:uid(),name:'Administration',active:true,subcategories:['Office Supplies','Postage','Software','Bank Fees']},
  {id:uid(),name:'Programs',active:true,subcategories:['Veterans Assistance','Community Service','Youth Programs']}];
 db.vendors=Array.isArray(db.vendors)?db.vendors:[];db.budgets=Array.isArray(db.budgets)?db.budgets:[];
 db.budgetSettings={yellow:75,red:100,...db.budgetSettings};db.themes={selected:'Light',custom:[],...db.themes};
 db.demo={active:false,loadedAt:'',...db.demo};db.auth={enabled:false,username:'admin',passwordHash:'',rememberMe:false,...db.auth};
 db.appVersion=PFMSCore.APP_VERSION;db.schemaVersion=PFMSCore.SCHEMA_VERSION;persist();
}
window.PFMS022Ensure=ensure;
const cats=(v='')=>db.categories.map(x=>`<option ${x.name===v?'selected':''}>${esc(x.name)}</option>`).join('');
const subs=(c,v='')=>(db.categories.find(x=>x.name===c)?.subcategories||[]).map(x=>`<option ${x===v?'selected':''}>${esc(x)}</option>`).join('');
function activeTheme(){return THEMES[db.themes.selected]||db.themes.custom.find(x=>x.name===db.themes.selected)?.colors||THEMES.Light}
function applyTheme(c=activeTheme()){const m={primary:'--navy',secondary:'--blue',accent:'--lime',border:'--line',background:'--light',card:'--card',menu:'--menu',button:'--button',success:'--green',warning:'--warn',danger:'--danger',text:'--text'};Object.entries(m).forEach(([k,v])=>document.documentElement.style.setProperty(v,c[k]));}

pages.splice(4,0,['categories','Categories'],['vendors','Vendors'],['budgets','Budgets']);pages.splice(-1,0,['themes','Themes']);
$('#nav').innerHTML=pages.map(([id,name])=>`<button class="navbtn" data-page="${id}">${name}</button>`).join('');
$$('.navbtn').forEach(button=>button.onclick=()=>go(button.dataset.page));
render.categories=()=>`<div class="toolbar"><button class="primary" id="addCat">Add Category</button></div><div class="card"><h2>Categories & Subcategories</h2><p class="muted">Unlimited classifications used by transactions, budgets, and reports.</p><div class="category-grid">${db.categories.map((c,i)=>`<section class="category-card"><div class="toolbar"><input data-cat="${i}" value="${esc(c.name)}"><button class="danger small delCat" data-i="${i}">Delete</button></div>${c.subcategories.map((s,j)=>`<div class="sub-row"><input data-subcat="${i}" data-j="${j}" value="${esc(s)}"><button class="danger small delSub" data-i="${i}" data-j="${j}">×</button></div>`).join('')}<button class="ghost small addSub" data-i="${i}">Add Subcategory</button></section>`).join('')}</div></div>`;
bind.categories=()=>{$('#addCat').onclick=()=>{db.categories.push({id:uid(),name:'New Category',active:true,subcategories:[]});save();go('categories')};$$('[data-cat]').forEach(x=>x.onchange=()=>{db.categories[+x.dataset.cat].name=x.value||'Unnamed Category';save()});$$('[data-subcat]').forEach(x=>x.onchange=()=>{db.categories[+x.dataset.subcat].subcategories[+x.dataset.j]=x.value;save()});$$('.addSub').forEach(x=>x.onclick=()=>{db.categories[+x.dataset.i].subcategories.push('New Subcategory');save();go('categories')});$$('.delSub').forEach(x=>x.onclick=()=>{db.categories[+x.dataset.i].subcategories.splice(+x.dataset.j,1);save();go('categories')});$$('.delCat').forEach(x=>x.onclick=()=>{if(confirm('Delete this category definition? Existing ledger text is preserved.')){db.categories.splice(+x.dataset.i,1);save();go('categories')}})};

render.vendors=()=>`<div class="toolbar"><button class="primary" id="addVendor">Add Vendor</button></div><div class="card"><h2>Vendor Directory</h2><div class="tablewrap"><table><thead><tr><th>Name</th><th>Contact</th><th>Phone</th><th>Email</th><th>Default Category</th><th>Notes</th><th></th></tr></thead><tbody>${db.vendors.map((v,i)=>`<tr>${['name','contact','phone','email'].map(k=>`<td><input data-v="${i}" data-k="${k}" value="${esc(v[k]||'')}"></td>`).join('')}<td><select data-v="${i}" data-k="category"><option></option>${cats(v.category)}</select></td><td><input data-v="${i}" data-k="notes" value="${esc(v.notes||'')}"></td><td><button class="danger small delVendor" data-i="${i}">Delete</button></td></tr>`).join('')||'<tr><td colspan="7">No vendors yet.</td></tr>'}</tbody></table></div></div>`;
bind.vendors=()=>{$('#addVendor').onclick=()=>{db.vendors.push({id:uid(),name:'New Vendor'});save();go('vendors')};$$('[data-v]').forEach(x=>x.onchange=()=>{db.vendors[+x.dataset.v][x.dataset.k]=x.value;save()});$$('.delVendor').forEach(x=>x.onclick=()=>{db.vendors.splice(+x.dataset.i,1);save();go('vendors')})};

function budgetRows(y,m){const a=PFMSCore.budgetActuals(db.ledger,y,m);return db.budgets.filter(x=>x.year==y&&(m?x.month==m:!x.month)).map(x=>{const key=x.level==='subcategory'?`subcategory:${x.category}:${x.subcategory}`:`category:${x.category}`,actual=a[key]||0,s=PFMSCore.budgetStatus(x.amount,actual,db.budgetSettings);return{...x,actual,remaining:PFMSCore.roundMoney(x.amount-actual),used:s.used,status:s.level}})}
render.budgets=()=>{const y=db.settings.budgetYear||nowYear(),m=db.settings.budgetMonth||'',rows=budgetRows(y,m);return`<div class="card"><div class="toolbar"><h2 style="margin-right:auto">Budget Center</h2><label>Year <input id="budYear" type="number" value="${y}"></label><label>View <select id="budMonth"><option value="">Annual</option>${Array.from({length:12},(_,i)=>`<option value="${i+1}" ${m==i+1?'selected':''}>${new Date(2026,i).toLocaleString('en',{month:'long'})}</option>`).join('')}</select></label><button class="primary" id="addBudget">Add Budget Line</button></div><label>Yellow at <input id="budYellow" type="number" value="${db.budgetSettings.yellow}">%</label> <label>Red at <input id="budRed" type="number" value="${db.budgetSettings.red}">%</label></div><div class="card" style="margin-top:16px"><div class="tablewrap"><table><thead><tr><th>Level</th><th>Category</th><th>Subcategory</th><th>Budget</th><th>Actual</th><th>Variance</th><th>% Used</th><th>Remaining</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.level}</td><td>${esc(x.category)}</td><td>${esc(x.subcategory||'—')}</td><td>${money(x.amount)}</td><td>${money(x.actual)}</td><td>${money(x.remaining)}</td><td>${x.used.toFixed(1)}%</td><td>${money(x.remaining)}</td><td><span class="budget-light ${x.status}">${x.status}</span></td><td><button class="ghost small editBudget" data-id="${x.id}">Edit</button> <button class="danger small delBudget" data-id="${x.id}">Delete</button></td></tr>`).join('')||'<tr><td colspan="10">No budget lines for this period.</td></tr>'}</tbody></table></div></div>`};
function budgetModal(x={}){modal(`<h2>${x.id?'Edit':'Add'} Budget Line</h2><div class="formgrid">${field('Year','year','number',x.year||db.settings.budgetYear||nowYear())}<div class="field"><label>Period</label><select name="month"><option value="">Annual</option>${Array.from({length:12},(_,i)=>`<option value="${i+1}" ${Number(x.month||db.settings.budgetMonth)===i+1?'selected':''}>${new Date(2026,i).toLocaleString('en',{month:'long'})}</option>`).join('')}</select></div><div class="field"><label>Level</label><select name="level"><option value="category">Category</option><option value="subcategory" ${x.level==='subcategory'?'selected':''}>Subcategory</option></select></div><div class="field"><label>Category</label><select name="category">${cats(x.category)}</select></div><div class="field"><label>Subcategory</label><select name="subcategory"><option></option>${subs(x.category||db.categories[0].name,x.subcategory)}</select></div>${field('Budget','amount','number',x.amount||'')}</div><div class="toolbar"><button class="primary" id="saveBudget">Save</button><button class="ghost" onclick="closeModal()">Cancel</button></div>`);const c=$('[name=category]'),s=$('[name=subcategory]');c.onchange=()=>s.innerHTML='<option></option>'+subs(c.value);$('#saveBudget').onclick=()=>{const v=formVals();v.id=x.id||uid();v.year=+v.year;v.month=v.month?+v.month:null;v.amount=+v.amount;if(v.amount<=0)return alert('Enter a valid budget.');if(v.level==='subcategory'&&!v.subcategory)return alert('Choose a subcategory.');const i=db.budgets.findIndex(b=>b.id===v.id);if(i<0)db.budgets.push(v);else db.budgets[i]=v;save();closeModal();go('budgets')}};
bind.budgets=()=>{$('#budYear').onchange=e=>{db.settings.budgetYear=+e.target.value;save();go('budgets')};$('#budMonth').onchange=e=>{db.settings.budgetMonth=e.target.value;save();go('budgets')};$('#budYellow').onchange=e=>{db.budgetSettings.yellow=+e.target.value;save();go('budgets')};$('#budRed').onchange=e=>{db.budgetSettings.red=+e.target.value;save();go('budgets')};$('#addBudget').onclick=()=>budgetModal();$$('.editBudget').forEach(x=>x.onclick=()=>budgetModal(db.budgets.find(b=>b.id===x.dataset.id)));$$('.delBudget').forEach(x=>x.onclick=()=>{db.budgets=db.budgets.filter(b=>b.id!==x.dataset.id);save();go('budgets')})};

const rgb=h=>{const n=parseInt(h.slice(1),16);return`${n>>16}, ${(n>>8)&255}, ${n&255}`},hex=s=>{const p=String(s).match(/\d+/g);return p?.length>=3?'#'+p.slice(0,3).map(x=>Math.min(255,+x).toString(16).padStart(2,'0')).join(''):null};
render.themes=()=>{const a=activeTheme();return`<div class="grid grid-2"><div class="card"><h2>Theme Library</h2><div class="theme-list">${[...Object.keys(THEMES),...db.themes.custom.map(x=>x.name)].map(n=>`<button class="theme-choice ${n===db.themes.selected?'active':''}" data-theme="${esc(n)}"><span style="background:${(THEMES[n]||db.themes.custom.find(x=>x.name===n).colors).accent}"></span>${esc(n)}</button>`).join('')}</div><div class="toolbar"><button class="ghost" id="exportTheme">Export</button><label class="ghost filebtn">Import<input id="importTheme" type="file" accept="application/json"></label></div></div><div class="card"><h2>Custom Theme Builder</h2><div class="field"><label>Name</label><input id="themeName" value="${esc(db.themes.selected+' Copy')}"></div><div class="color-grid">${CK.map(k=>`<div class="color-field"><label>${pretty(k)}</label><input type="color" data-color="${k}" value="${a[k]}"><input data-hex="${k}" value="${a[k]}"><input data-rgb="${k}" value="${rgb(a[k])}"></div>`).join('')}</div><div class="toolbar"><button class="primary" id="saveTheme">Save Theme</button><button class="ghost" id="dupTheme">Duplicate</button>${db.themes.custom.some(x=>x.name===db.themes.selected)?'<button class="danger" id="delTheme">Delete</button>':''}</div><p class="muted">HEX, RGB, and color controls preview instantly across PFMS.</p></div></div>`};
function colors(){return Object.fromEntries(CK.map(k=>[k,$(`[data-color="${k}"]`).value]))}
bind.themes=()=>{$$('.theme-choice').forEach(x=>x.onclick=()=>{db.themes.selected=x.dataset.theme;save();applyTheme();go('themes')});$$('[data-color]').forEach(x=>x.oninput=()=>{const k=x.dataset.color;$(`[data-hex="${k}"]`).value=x.value;$(`[data-rgb="${k}"]`).value=rgb(x.value);applyTheme(colors())});$$('[data-hex]').forEach(x=>x.onchange=()=>{const k=x.dataset.hex;if(/^#[0-9a-f]{6}$/i.test(x.value)){$(`[data-color="${k}"]`).value=x.value;applyTheme(colors())}});$$('[data-rgb]').forEach(x=>x.onchange=()=>{const k=x.dataset.rgb,v=hex(x.value);if(v){$(`[data-color="${k}"]`).value=v;$(`[data-hex="${k}"]`).value=v;applyTheme(colors())}});const saveT=s=>{let name=$('#themeName').value.trim()||'Custom';if(s)name+=' Copy';const r={name,colors:colors()},i=db.themes.custom.findIndex(x=>x.name===name);i<0?db.themes.custom.push(r):db.themes.custom[i]=r;db.themes.selected=name;save();applyTheme();go('themes')};$('#saveTheme').onclick=()=>saveT(false);$('#dupTheme').onclick=()=>saveT(true);$('#delTheme')?.addEventListener('click',()=>{db.themes.custom=db.themes.custom.filter(x=>x.name!==db.themes.selected);db.themes.selected='Light';save();applyTheme();go('themes')});$('#exportTheme').onclick=()=>download(`PFMS_Theme_${db.themes.selected}.json`,JSON.stringify({product:'PFMS Theme',version:1,name:db.themes.selected,colors:activeTheme()},null,2),'application/json');$('#importTheme').onchange=e=>{const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.name||!CK.every(k=>/^#[0-9a-f]{6}$/i.test(x.colors[k])))throw 0;db.themes.custom.push(x);db.themes.selected=x.name;save();applyTheme();go('themes')}catch{alert('Invalid PFMS theme file.')}};r.readAsText(e.target.files[0])}};

function demo(){
 const y=nowYear(),D=m=>`${y}-${m}`,tx=(d,t,desc,pay,amt,fund,cat,sub='',allocations=[])=>({id:uid(),date:d,type:t,description:desc,payee:pay,fund,account:'General Checking',category:cat,subcategory:sub,amount:amt,check:'',status:'Posted',notes:'Editable demonstration record',source:'Demo Data',created:new Date().toISOString(),allocations});
 db.demo={active:true,loadedAt:new Date().toISOString()};db.vendors=[{id:uid(),name:'Southern California Edison',contact:'Business Services',phone:'800-655-4555',category:'Building',notes:'Electric utility'},{id:uid(),name:'R & S Beverage',category:'Canteen',notes:'Beverage distributor'},{id:uid(),name:'Costco',category:'Kitchen'}];
 db.ledger=[tx(D('01-05'),'Income','Membership dues','Members',1850,'General Fund','Administration'),tx(D('01-12'),'Income','Merchant settlement','Merchant Deposits',2500,'General Fund','Canteen','',[{fund:'General Fund',account:'General Checking',category:'Administration',subcategory:'',amount:700},{fund:'Kitchen Fund',account:'General Checking',category:'Kitchen',subcategory:'',amount:900},{fund:'Canteen / Club Fund',account:'General Checking',category:'Canteen',subcategory:'',amount:600},{fund:'Relief Fund',account:'General Checking',category:'Programs',subcategory:'Veterans Assistance',amount:300}]),tx(D('01-14'),'Expense','Beverage inventory','R & S Beverage',842.16,'Canteen / Club Fund','Canteen','Beer'),tx(D('01-18'),'Expense','Kitchen supplies','Costco',516.42,'Kitchen Fund','Kitchen','Meat'),tx(D('02-03'),'Expense','Electric service','Southern California Edison',438.77,'Post Home / Building Fund','Building','Electrical'),tx(D('03-01'),'Expense','HVAC repair','High Desert Mechanical',725,'Post Home / Building Fund','Building','HVAC')];
 db.utilities=[{vendor:'Southern California Edison',amount:438.77,fund:'Post Home / Building Fund',account:'General Checking',dueDay:'15',notes:'Electric service',status:'Open',check:''}];db.approvals=[{description:'Replace kitchen refrigerator',payee:'Restaurant Supply',motionBy:'Chris Harvey',secondedBy:'Phil Navarro',amount:1895,fund:'Kitchen Fund',account:'General Checking',meetingDate:D('03-08'),notes:'Approved',status:'Open',check:''}];db.reimbursements=[{payee:'Michael Croy II',description:'Office supplies',motionBy:'Chris Harvey',secondedBy:'Phil Navarro',amount:86.34,fund:'General Fund',account:'General Checking',meetingDate:D('03-08'),notes:'Receipts attached',status:'Open',check:''}];db.budgets=[{id:uid(),year:y,month:null,level:'category',category:'Canteen',subcategory:'',amount:12000},{id:uid(),year:y,month:null,level:'category',category:'Kitchen',subcategory:'',amount:9000},{id:uid(),year:y,month:null,level:'category',category:'Building',subcategory:'',amount:10000},{id:uid(),year:y,month:1,level:'subcategory',category:'Canteen',subcategory:'Beer',amount:1000}];persist();go('dashboard');alert('Demo Mode loaded. Every record is editable.')};

render.settings=()=>`<div class="settings-tabs">${['General','Organization','Reports','Backup','Demo Data','Local Login'].map((x,i)=>`<button class="tab ${i?'':'active'}" data-stab="${x.replace(' ','').toLowerCase()}">${x}</button>`).join('')}</div>
<div class="settings-panel" data-panel="general"><div class="card"><h2>General</h2><p>PFMS Alpha 0.2.2 Demo Edition is local, offline, and fully editable.</p><button class="ghost" id="appearance">Appearance</button><button class="ghost" id="fundSetup">Funds</button><button class="ghost" id="catSetup">Categories</button></div></div>
<div class="settings-panel hidden" data-panel="organization"><div class="card"><h2>Organization</h2><div class="formgrid"><div class="field"><label>Profile</label><select disabled><option>VFW (verified)</option><option>Other profiles arrive in Alpha 0.3</option></select></div>${field('Name','orgName','text',db.org.name)}${field('Unit / Post Number','orgNum','text',db.org.number)}${field('Department / State','orgDept','text',db.org.department)}${field('Fiscal Year Start','fiscalStart','text',db.org.fiscalYearStart)}</div><button class="primary" id="saveOrg">Save</button></div></div>
<div class="settings-panel hidden" data-panel="reports"><div class="card"><h2>Reports</h2><div class="field"><label>Default Monthly Profile</label><select id="reportProfile"><option value="meeting">Meeting Copy</option><option value="audit" ${db.reportSettings.defaultProfile==='audit'?'selected':''}>Audit Copy</option></select></div><button class="primary" id="saveReport">Save</button></div></div>
<div class="settings-panel hidden" data-panel="backup"><div class="card"><h2>Backup & Restore</h2><p>Complete backups include budgets, classifications, vendors, themes, demo state, and login settings.</p><button class="ghost" onclick="exportBackup()">Export Complete Backup</button><label class="ghost filebtn">Restore<input id="setRestore" type="file" accept="application/json"></label><button class="danger" id="resetAll">Reset All Data</button></div></div>
<div class="settings-panel hidden" data-panel="demodata"><div class="card"><h2>Demo Data</h2><p><span class="badge ${db.demo.active?'green':''}">${db.demo.active?'Demo Mode Active':'Demo Mode Off'}</span></p><p>Loads realistic VFW data into the production database. All demo records remain editable.</p><button class="primary" id="loadDemo">${db.demo.active?'Reset Demo Data':'Load Demo Data'}</button><button class="ghost" onclick="exportBackup()">Backup First</button></div></div>
<div class="settings-panel hidden" data-panel="locallogin"><div class="card"><h2>Local Login</h2><p class="muted">Single-machine access convenience; not cloud identity or encryption.</p><label><input id="authOn" type="checkbox" ${db.auth.enabled?'checked':''}> Require login</label><div class="formgrid">${field('Username','authUser','text',db.auth.username)}${field('New Password','authPass','password','')}<div class="field"><label>Remember Me</label><select id="authRemember"><option value="false">Require login after restart</option><option value="true" ${db.auth.rememberMe?'selected':''}>Remember this machine</option></select></div></div><button class="primary" id="saveAuth">Save</button><button class="ghost" id="lockNow">Lock Now</button></div></div>`;
bind.settings=()=>{$$('[data-stab]').forEach(x=>x.onclick=()=>{$$('[data-stab]').forEach(y=>y.classList.toggle('active',x===y));$$('[data-panel]').forEach(y=>y.classList.toggle('hidden',y.dataset.panel!==x.dataset.stab))});$('#appearance').onclick=()=>go('themes');$('#fundSetup').onclick=()=>go('funds');$('#catSetup').onclick=()=>go('categories');$('#saveOrg').onclick=()=>{db.org.name=$('[name=orgName]').value;db.org.number=$('[name=orgNum]').value;db.org.department=$('[name=orgDept]').value;db.org.fiscalYearStart=$('[name=fiscalStart]').value;save()};$('#saveReport').onclick=()=>{db.reportSettings.defaultProfile=$('#reportProfile').value;save()};$('#setRestore').onchange=restoreBackup;$('#resetAll').onclick=()=>{if(confirm('Erase all PFMS data?')){db=clone(seed);ensure();go('dashboard')}};$('#loadDemo').onclick=()=>{if(confirm('Demo Mode replaces the active database. Export a backup first if needed. Continue?')){db=clone(seed);ensure();demo()}};$('#saveAuth').onclick=async()=>{const p=$('[name=authPass]').value;if($('#authOn').checked&&!p&&!db.auth.passwordHash)return alert('Enter a password first.');db.auth.enabled=$('#authOn').checked;db.auth.username=$('[name=authUser]').value||'admin';db.auth.rememberMe=$('#authRemember').value==='true';if(p)db.auth.passwordHash=await hash(p);sessionStorage.setItem('pfms-auth','1');save()};$('#lockNow').onclick=()=>{sessionStorage.removeItem('pfms-auth');localStorage.removeItem('pfms-remember');login()}};
async function hash(v){const b=new TextEncoder().encode('PFMS-0.2.2|'+v);if(crypto.subtle){const h=await crypto.subtle.digest('SHA-256',b);return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}let h=2166136261;b.forEach(x=>{h^=x;h=Math.imul(h,16777619)});return(h>>>0).toString(16)}
function login(){if(!db.auth.enabled||sessionStorage.getItem('pfms-auth')==='1'||(db.auth.rememberMe&&localStorage.getItem('pfms-remember')==='1'))return;document.body.insertAdjacentHTML('beforeend',`<div class="login-screen" id="login"><div class="login-card"><img src="pfms-logo.png"><h1>PFMS</h1><p>Alpha 0.2.2 Demo Edition</p>${field('Username','loginUser')}${field('Password','loginPass','password')}<label><input id="remember" type="checkbox"> Remember Me</label><button class="primary" id="signin">Sign In</button><p id="loginError" class="danger-text"></p></div></div>`);$('#signin').onclick=async()=>{if($('[name=loginUser]').value!==db.auth.username||await hash($('[name=loginPass]').value)!==db.auth.passwordHash)return $('#loginError').textContent='Username or password is incorrect.';sessionStorage.setItem('pfms-auth','1');if($('#remember').checked)localStorage.setItem('pfms-remember','1');$('#login').remove()}};

const oldGo=go;go=p=>{oldGo(p);$('#demoBadge')?.remove();if(db.demo.active)$('.brand').insertAdjacentHTML('beforeend','<span id="demoBadge" class="demo-badge">DEMO</span>');applyTheme()};
exportBackup=()=>download(`PFMS_Alpha_0_2_2_Backup_${date()}.json`,JSON.stringify(PFMSCore.backupEnvelope(db),null,2),'application/json');window.exportBackup=exportBackup;
ensure();applyTheme();go(current);login();
})();
